variables:
    # Configure mysql service (https://hub.docker.com/_/mysql/)
    MYSQL_DATABASE: wordpress_tests
    MYSQL_ROOT_PASSWORD: mysql

stages:
    - verify
    - test
    - deploy

PHPCS:PHP7.2:MySQL:
    stage: verify
    image: gagan0123/php:7.2
    script:
        - phpcs
    allow_failure: true

WP-Latest:PHP5.6:
    stage: test
    image: gagan0123/php:5.6
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql latest true
        - phpunit --configuration phpunit.xml.dist

WP-Latest:PHP7.2:
    stage: test
    image: gagan0123/php:7.2
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql latest true
        - phpunit --configuration phpunit.xml.dist

WP-Latest:PHP7.3:
    stage: test
    image: gagan0123/php:7.3
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql latest true
        - phpunit --configuration phpunit.xml.dist
    allow_failure: true

WP-Nightly:PHP5.6:
    stage: test
    image: gagan0123/php:5.6
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql nightly true
        - phpunit --configuration phpunit.xml.dist
    allow_failure: true

WP-Nightly:PHP7.2:
    stage: test
    image: gagan0123/php:7.2
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql nightly true
        - phpunit --configuration phpunit.xml.dist
    allow_failure: true

WP-Nightly:PHP7.3:
    stage: test
    image: gagan0123/php:7.3
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql nightly true
        - phpunit --configuration phpunit.xml.dist
    allow_failure: true

WP4.9.9:PHP7.2:
    stage: test
    image: gagan0123/php:7.2
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql 4.9.9 true
        - phpunit --configuration phpunit.xml.dist

WP4.8.8:PHP7.2:
    stage: test
    image: gagan0123/php:7.2
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql 4.8.8 true
        - phpunit --configuration phpunit.xml.dist

WP4.7.12:PHP7.2:
    stage: test
    image: gagan0123/php:7.2
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql 4.7.12 true
        - phpunit --configuration phpunit.xml.dist

WP4.6.13:PHP5.6:
    stage: test
    image: gagan0123/php:5.6
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql 4.6.13 true
        - phpunit --configuration phpunit.xml.dist

WP4.5.16:PHP5.6:
    stage: test
    image: gagan0123/php:5.6
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql 4.5.16 true
        - phpunit --configuration phpunit.xml.dist

WP4.4.17:PHP5.6:
    stage: test
    image: gagan0123/php:5.6
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql 4.4.17 true
        - phpunit --configuration phpunit.xml.dist

WP4.3.18:PHP5.6:
    stage: test
    image: gagan0123/php:5.6
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql 4.3.18 true
        - phpunit --configuration phpunit.xml.dist

WP4.2.22:PHP5.6:
    stage: test
    image: gagan0123/php:5.6
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql 4.2.22 true
        - phpunit --configuration phpunit.xml.dist

WP4.1.25:PHP5.6:
    stage: test
    image: gagan0123/php:5.6
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql 4.1.25 true
        - phpunit --configuration phpunit.xml.dist

WP4.0.25:PHP5.6:
    stage: test
    image: gagan0123/php:5.6
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql 4.0.25 true
        - phpunit --configuration phpunit.xml.dist

Deploy:
    stage: deploy
    environment: 
        name: deployment
    image: gagan0123/svn:latest
    when: manual
    script:
        - bash bin/gitlab-deploy.sh